# Generated by Django 6.1 on 2026-09-01 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.barbero')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.horario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fecha', 'horario'), name='cita_fecha_horario_unicos')],
            },
        ),
    ]
