# Generated by Django 6.1.1 on 2026-09-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('mesa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='restaurante.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_contratacion', models.DateField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='restaurante.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('plato_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='restaurante.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='restaurante.cliente')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='restaurante.mesa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mesa', 'fecha', 'hora'), name='reserva_mesa_fecha_hora_unica'), models.CheckConstraint(condition=models.Q(('estado__in', ['pendiente', 'confirmada', 'cancelada'])), name='reserva_estado_valido')],
            },
        ),
    ]
