# Generated by Django 6.1.1 on 2026-09-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_personas__gt', 0)), name='reserva_cantidad_positiva'),
        ),
    ]
