# Generated by Django 6.1.1 on 2026-09-13 08:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_reserva_reserva_cantidad_positiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('detalle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_reserva', to='restaurante.plato')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='restaurante.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='platos',
            field=models.ManyToManyField(blank=True, related_name='reservas', through='restaurante.DetalleReserva', to='restaurante.plato'),
        ),
        migrations.CreateModel(
            name='FichaReserva',
            fields=[
                ('ficha_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ocasion', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='restaurante.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReserva',
            fields=[
                ('solicitud_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('atendida', models.BooleanField(default=False)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='restaurante.reserva')),
            ],
        ),
        migrations.AddConstraint(
            model_name='detallereserva',
            constraint=models.UniqueConstraint(fields=('reserva', 'plato'), name='detalle_reserva_plato_unico'),
        ),
        migrations.AddConstraint(
            model_name='detallereserva',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detalle_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detallereserva',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='detalle_precio_no_negativo'),
        ),
    ]
