# Generated by Django 6.1.1 on 2026-09-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_detallereserva_reserva_platos_fichareserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='existencias',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
